### PR TITLE
example addresses: change to ff35:30:2001:db8:f1::8000:x

### PR DESCRIPTION
**Pull request by chrysn**
The generated address failed to follow the guidance of RFC 3307 and
set the first bit of the Group ID.

### CODE REVIEW

**Comment by EskoDijk** [comment]
Since the example prefix is 2001:db8::/32 , I would assume the plen field is also set to 32, so we would get:
ff35:**2**0:2001:db8::8000:x

Or is there a reason here to use plen=0x30 (48) bits ?

**Comment by chrysn** [comment]
On Mon, Oct 12, 2020 at 02:42:16AM -0700, Esko Dijk wrote:
> Or is there a reason here to use plen=0x30 (48) bits ?

Throughout the examples, we use the third word to distinguish between
separate logically distinct examples (2001:db8:1:: .. 2001:db8:4::), so
it seemed logical to take a /48 for this example as well. (Although in
keeping with the other appendix that uses 2001:db8:f0::, something like
2001:db8:e0::/48 and thus ff35:30:2001:db8:e0::1 would enhance
consistency).

**Comment by EskoDijk** [comment]
Ok, thanks - I see - so in example nr 4 the prefix 2001:db8:4/48 is used, then the mcast address would become
ff35:30:2001:db8:4::8000:x  
right? If the ':4' is omitted it looks like a prefix 2001:db8/32 is being used.

**Comment by chrysn** [comment]
The last commit on this series (c4d24f38342a6a6e0074a26dfd88db302b62d47c) now has something in the original addresses 3rd word (2001:db8:f1::/48) to make the choice of 30 in the prefix length more understandable, and for consistency.

**Pull request merged**
