### PR TITLE
added registree-ep to remove ambiguities in tet

### PR DESCRIPTION
**Pull request by petervanderstok**

### CODE REVIEW

**Comment by petervanderstok** [comment]
I added registree-ep, because the text is not always clear which endpoint or CT (client) is doing the registration. Also changed endpoint to registration for some phrases

**Comment by chrysn** [comment]
I've played with the thought of renaming "endpoints" to "registrations" and discarded it for causing more confusion, but "registree endpoint" sounds good and descriptive.

Do you want to wait for other authors' comments on it or shall we just merge it?

**Comment by chrysn** [comment]
On first reading the proposed change I probably misunderstood its intention (I thought it'd refer to the registration the endpoint obtains (linked to the registration resource) and not the endpoint-as-in-coap-terms -- but that was careless patch-reading of mine.

Nonetheless, clearer terminology is something we should have, and this can be a step towards it.

**Comment by petervanderstok** [comment]
it is the ep to be registered. In the text it is not always clear what
is registered and what is doing the registering.
I exchanged endpoint with registry when endpoint was misused.
Also client and server are ambiguous terms sometimes.

For me it can be merged. Probably you will find other examples in the
text where ep ,rg or cl-s are overloaded or just wrong..

Peter
chrysn schreef op 2018-06-18 17:02:

> On first reading the proposed change I probably misunderstood its intention (I thought it'd refer to the registration the endpoint obtains (linked to the registration resource) and not the endpoint-as-in-coap-terms -- but that was careless patch-reading of mine. 
> 
> Nonetheless, clearer terminology is something we should have, and this can be a step towards it. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/pull/138#issuecomment-398085283
[2]

**Pull request merged**
