### PR TITLE
2020-02-21 changes

### PR DESCRIPTION
**Pull request by chrysn**
These roll up several small changes from #222 as well as the explicit "how to find the RD in DNS-SD".

@petervanderstok, @cabo and @mjkoster, please have a look (especially at the first commit).

### CODE REVIEW

**Comment by petervanderstok** [comment]
HI Chris,

thanks for taking this up

 1 typo and 1 suggestion below.

cheerio,

Peter

Using DNS-SD to discover a resource directory {#rd-using-dnssd}

A resource directory can advertise its resources in DNS-SD
using the service names `_rd._udp`, `_rd-lookup-res._udp` and
`_rd_lookup-ep._udp`
for its Directory Resource, its resource lookup and endpoint lookup
resource, respectively.
A "path" key SHOULD be set, and indicate the path on the server
(starting with a slash).

By combining the protocol to use (CoAP is implied for those names)
pvds==>
I don't uderstand what you mean here...
the words "combining" and "protocol to use" drop from the sky.
may be s/combining/specifying/
may be precede by "For example" to make sure that the refrence to
rd-dns-sd remains informative.
==>
with the host name and port given in the SRV record
and the path from the TXT record,
the discovering client can perform RD and URI discovery in a single
step.

When the "path" key is absent, the client MUST discovery the URIs on the
server according to {{discovery}}.
pvds==>
s/discovery/discover/
==>

This section is a concrete application of the more generic mechanism
that is being developed as {{I-D.ietf-core-rd-dns-sd}}.
pvds==>
s/a concrete application/an example/
==>
chrysn schreef op 2020-02-23 18:27:

> These roll up several small changes from #222 [1] as well as the explicit "how to find the RD in DNS-SD". 
> 
> @petervanderstok [2], @cabo [3] and @mjkoster [4], please have a look (especially at the first commit). 
> -------------------------
> 
> YOU CAN VIEW, COMMENT ON, OR MERGE THIS PULL REQUEST ONLINE AT:
> 
> https://github.com/core-wg/resource-directory/pull/224 
> 
> COMMIT SUMMARY
> 
> * State explicitly how to find an RD using DNS-SD
> * HTTP terminology: use "header field"
> * Reference "URN"s RFC when first used
> * RDAO option: Don't insist on a value
> * editorial around section 4.3
> * (typo)
> * Make HTTP example be actual HTTP
> * fixup! (typo)
> * Fix mismatches between code names and numbers
> * "(full) URIs" instead of "absiolute references"
> * Endpoint type registry: Add reference field
> 
> FILE CHANGES
> 
> * M draft-ietf-core-resource-directory.md [5] (91)
> 
> PATCH LINKS:
> 
> * https://github.com/core-wg/resource-directory/pull/224.patch
> * https://github.com/core-wg/resource-directory/pull/224.diff
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [6], or unsubscribe [7].
 

Links:
------
[1] https://github.com/core-wg/resource-directory/issues/222
[2] https://github.com/petervanderstok
[3] https://github.com/cabo
[4] https://github.com/mjkoster
[5] https://github.com/core-wg/resource-directory/pull/224/files#diff-0
[6]
https://github.com/core-wg/resource-directory/pull/224?email_source=notifications&amp;email_token=ADCZGQNDIRQITTANUUMEN3TREKWXLA5CNFSM4KZ4KHV2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IPSKIPQ
[7]

**Comment by chrysn** [comment]
> I don't uderstand what you mean here...
the words "combining" and "protocol to use" drop from the sky.
may be s/combining/specifying/

Wording changed to be more explicit that this is something defined here (as was Stuart's guidance on the topic of protocol negotiation -- "don't").

> may be precede by "For example" to make sure that the refrence to
rd-dns-sd remains informative.

and

> pvds==>
s/a concrete application/an example/

This is not an example -- we're defining those service names and their meaning in here (as emphasised by the updated wording).

So maybe there's a better word for "we bake a subset of what's currently there and hope that it'll be compatible with what that will come out to be", but I don't know any.

>server according to {{discovery}}.
pvds==>
s/discovery/discover/

I don't follow -- that's the label of the "URI Discovery" section.

**Comment by petervanderstok** [comment]
chrysn schreef op 2020-02-24 15:00

>> pvds==>
>> s/a concrete application/an example/
> 
> This is not an example -- we're defining those service names and their meaning in here (as emphasised by the updated wording).
> pvds==>
> may be: and example of the use of the defined services following the syntax specified in {{rd- dns-sd}}
> ==> 
> 
> So maybe there's a better word for "we bake a subset of what's currently there and hope that it'll be compatible with what that will come out to be", but I don't know any.
> 
>> server according to {{discovery}}.
>> pvds==>
>> s/discovery/discover/
> 
> I don't follow -- that's the label of the "URI Discovery" section.
> 
> pvds==>
> sorry, missed the braces
> ==> 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/pull/224?email_source=notifications&amp;email_token=ADCZGQLTVDWC27JU7F3WWWLREPHH5A5CNFSM4KZ4KHV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMX4FTA#issuecomment-590332620
[2]

**Comment by mjkoster** [comment]
That text looks better. Instead of "is being developed as" future tense, we could say "is specified in".

This section is a concrete application of the more generic mechanism that is being developed as {{I-D.ietf-core-rd-dns-sd}}.

**Comment by chrysn** [comment]
Just as you were writing I found that I didn't really capture the WG outcome; please have a look at #228 that strips things down further -- less powerful, but simpler and more aligned with the IETF106 discussion.

**Comment by mjkoster** [comment]
Yes, that looks good!

Best regards,

Michael

**Pull request closed without merging**
